# Utility to scaffold minimal project templates
import os

TEMPLATE_PY = """# minimal project
def main():
    print("Hello from scaffolded project")

if __name__ == '__main__':
    main()
"""

def scaffold_basic_python_project(path: str, name: str):
    os.makedirs(path, exist_ok=True)
    with open(os.path.join(path, "main.py"), "w", encoding="utf-8") as f:
        f.write(TEMPLATE_PY)
    with open(os.path.join(path, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# {name}\nScaffolded project generated by Telegram AI Bot")
